name: Deploy React App to S3

on:
  push:
    branches:
      - main # trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest # use ubuntu virtual machine
    steps:
      - uses: actions/checkout@v2 # checkout the repo
      - uses: actions/setup-node@v2 # setup node environment
        with:
          node-version: '18' # use node version 18
      - name: Create .env.local file # add this step
         run: echo "REACT_APP_OPEN_AI_API_KEY=${{ secrets.REACT_APP_OPEN_AI_API_KEY }}" > .env.local # create the file from the secret
      - run: npm install # install dependencies
      - run: npm run build # build the app
      - uses: jakejarvis/s3-sync-action@master # use s3-sync-action to sync the app to S3       
        env:
          REACT_APP_OPEN_AI_API_KEY: ${{ secrets.REACT_APP_OPEN_AI_API_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }} # S3 bucket name
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS secret key
          AWS_REGION: 'ap-southeast-2' # AWS region
          SOURCE_DIR: 'build' # source directory to sync
